### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by digitalit** [LarryEitel/phpdock#1]
Can i run multiple sites with one phpdock?

**Comment by LarryEitel** [comment]
This repo is/was more of an effort to wrap my mind around Docker. Please check out [this repo](https://github.com/LarryEitel/laravel-laradock-phpstorm) instead. There are ways to use a proxy to direct traffic to respective sites running on different ports. I am on 'vacation' and so it is not convenient to try and elaborate right now. :)

**Comment by digitalit** [comment]
Ok, thanx.
